### ISSUE TITLE
SetValidation only works when at most 0 validation keys are set and 1 are present

### ISSUE THREAD

**Issue by anhcao142** [ndau/ndau#9]
Hi, I'm getting this error when trying to resubmit setValidation for my address. Is it mean that for an address I can only setValidation for it once?

**Comment by jsgjnr** [comment]
SetValidation is only used to set initial validation keys and script, to update validation keys and script, use the following transaction:

https://ndau.io/techdocs/transactions.html#changevalidation

-- John

**Comment by anhcao142** [comment]
Thanks for your information
